### ISSUE TITLE
Navigazione tra pagine, implementazione tasto indietro

### ISSUE THREAD

**Issue by MarcoL82** [Cosiam-srl/GestionaleCosiam#10]

**Comment by Eulab-EugenioRenna** [comment]
Integrato pulsante per tornare indietro nella ui 
<img width="335" alt="Screenshot 2024-10-24 alle 11 11 56" src="https://github.com/user-attachments/assets/71cf0f2f-2426-4444-bceb-96c7e7b0af24">
