### ISSUE TITLE
Miglioramento grafico costi/ricavi sezione dashboard

### ISSUE THREAD

**Issue by francescogrecocosiam** [Cosiam-srl/GestionaleCosiam#13]
Modifica linea utile e sosituzione linee costi/ricavi con barre come da immagine allegata
![Prima](https://github.com/user-attachments/assets/f1416e49-d1c4-433a-a919-d3dd957facfb)
![Grafico tipo Agicap](https://github.com/user-attachments/assets/a5c51c10-971e-4a8b-aea9-07785b37e500)

**Comment by Eulab-EugenioRenna** [comment]
Implementato nuovo grafico 

<img width="1215" alt="Screenshot 2024-10-25 alle 12 34 07" src="https://github.com/user-attachments/assets/eff999ad-b847-483f-912e-2e3604bad871">

Migliorato lo zoom selezione e implementato modale di conferma download report 

<img width="1588" alt="Screenshot 2024-10-25 alle 12 47 02" src="https://github.com/user-attachments/assets/950a0839-a696-48e8-b63c-f6df1a7638f1">

**Comment by Eulab-EugenioRenna** [comment]
1. separatore Migliaia
2. costi/ricavi stessa riga
3. inserire simbolo €
4. inserire predefiniti tempo (6 mesi , 1 anno , ytd)
5. Linea utile incrementale

**Comment by Eulab-EugenioRenna** [comment]
<img width="922" alt="Screenshot 2024-10-28 alle 15 23 32" src="https://github.com/user-attachments/assets/7196a0f7-33eb-4367-8144-0f33dc0698f5">
<img width="1213" alt="Screenshot 2024-10-28 alle 15 24 13" src="https://github.com/user-attachments/assets/d7296a9b-d0d6-4b4a-b92c-42b0e1909a88">
