### ISSUE TITLE
Formattazione testi alfabetici in tutte le schede

### ISSUE THREAD

**Issue by MarcoL82** [Cosiam-srl/GestionaleCosiam#2]
Formattazione testi alfabetici, i testi dovranno essere con la prima lettera maiuscola e le altre minuscole

**Comment by Eulab-EugenioRenna** [comment]
Sistemata formattazione colonna
<img width="262" alt="Screenshot 2024-10-24 alle 12 11 49" src="https://github.com/user-attachments/assets/568266ee-b82f-42e1-b567-d2d1e4e93d74">
