### ISSUE TITLE
Scheda Fornitori in ordine alfabetico

### ISSUE THREAD

**Issue by MarcoL82** [Cosiam-srl/GestionaleCosiam#4]
Inserire i fornitori in ordine alfabetico. 
Aprendo la scheda vederli sempre in ordine alfabetico

**Comment by Eulab-EugenioRenna** [comment]
Sistemato ordine alfabetico
<img width="262" alt="Screenshot 2024-10-24 alle 12 11 49" src="https://github.com/user-attachments/assets/3a6b1f0e-4b8b-4b8b-bb25-1a2e86531160">
