### ISSUE TITLE
Scheda Fornitori - Lista servizi

### ISSUE THREAD

**Issue by MarcoL82** [Cosiam-srl/GestionaleCosiam#5]
Quando si aggiunge un servizio inserire la possibilità di vedere la lista di 30/50 servizi.
Ad oggi se ne vedono 4 (se non sbaglio) e poi devo cambiare pagina, è molto scomodo

**Comment by Eulab-EugenioRenna** [comment]
Aggiunta la possibilità di scegliere il numero di righe da far comparire
<img width="1791" alt="Screenshot 2024-10-24 alle 14 38 40" src="https://github.com/user-attachments/assets/1e1fdae9-95f9-46eb-bf23-05fac6a4353a">
